"""Add season_number and episode_number columns to MediaItem

Revision ID: 5a3121afd767
Revises: add_revoked_at_column
Create Date: 2025-11-09 12:07:23.590764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a3121afd767'
down_revision = 'add_revoked_at_column'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('episode_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_items', schema=None) as batch_op:
        batch_op.drop_column('episode_number')
        batch_op.drop_column('season_number')

    # ### end Alembic commands ###
