import { useState, useSyncExternalStore } from 'react';
import { ApiReferenceReact } from '@scalar/api-reference-react';
import '@scalar/api-reference-react/style.css';

import { Button } from '../components/ui/button';
import { useAlerts } from '../contexts/AlertContext';
import { getAuthSnapshot, subscribeToAuthStore } from '../store/authStore';

const copyToClipboard = (value: string) => {
  if (!value) return false;

  const textarea = document.createElement('textarea');
  textarea.value = value;
  textarea.setAttribute('readonly', '');
  textarea.style.position = 'absolute';
  textarea.style.left = '-9999px';
  document.body.appendChild(textarea);
  textarea.select();

  const success = document.execCommand('copy');
  document.body.removeChild(textarea);
  return success;
};

export const ApiDocsPage = () => {
  const { success, error: showError, info } = useAlerts();
  const auth = useSyncExternalStore(subscribeToAuthStore, getAuthSnapshot, getAuthSnapshot);
  const [copying, setCopying] = useState(false);
  const hasAccessToken = Boolean(auth.accessToken);

  const handleCopyAccessToken = async () => {
    if (!auth.accessToken) {
      info('No access token available yet. Try refreshing your session.');
      return;
    }

    if (copying) return;
    setCopying(true);

    try {
      if (navigator.clipboard?.writeText) {
        await navigator.clipboard.writeText(auth.accessToken);
      } else if (!copyToClipboard(auth.accessToken)) {
        throw new Error('Clipboard unavailable');
      }

      success('Access token copied. Paste it into Scalar Bearer auth.');
    } catch (err) {
      console.error('Failed to copy access token', err);
      showError('Failed to copy access token. Please copy it manually.');
    } finally {
      setCopying(false);
    }
  };

  return (
    <div className="flex h-screen w-full flex-col">
      <div className="border-b bg-background">
        <div className="mx-auto flex w-full max-w-5xl flex-wrap items-center justify-between gap-3 px-4 py-3">
          <div className="space-y-1">
            <h1 className="text-lg font-semibold">API Docs</h1>
            <p className="text-sm text-muted-foreground">
              Copy your current access token and paste it into the Bearer auth in Scalar.
            </p>
          </div>
          <Button type="button" onClick={handleCopyAccessToken} disabled={!hasAccessToken || copying}>
            {copying ? 'Copying...' : 'Copy Access Token'}
          </Button>
        </div>
      </div>
      <div className="min-h-0 flex-1">
        <ApiReferenceReact
          configuration={{
            // Point Scalar to OpenAPI 3.1 spec generated by flask-openapi3 (api_v2)
            url: '/admin/api/v2/openapi/openapi.json',
            theme: 'default',
            layout: 'modern',
            darkMode: document.documentElement.classList.contains('dark'),
            searchHotKey: 'k',
            showSidebar: true,
          }}
        />
      </div>
    </div>
  );
};

export default ApiDocsPage;
