import { ApiReferenceReact } from '@scalar/api-reference-react';
import '@scalar/api-reference-react/style.css';

export const ApiDocsPage = () => {
  return (
    <div className="h-screen w-full">
      <ApiReferenceReact
        configuration={{
          // Point Scalar to OpenAPI 3.1 spec generated by flask-openapi3 (api_v2)
          url: '/admin/api/v2/openapi/openapi.json',
          theme: 'default',
          layout: 'modern',
          darkMode: document.documentElement.classList.contains('dark'),
          searchHotKey: 'k',
          showSidebar: true,
        }}
      />
    </div>
  );
};

export default ApiDocsPage;
